export const CAT_ARRAY = [
  {breed: 'Abyssinian', catName: 'Abby', id: 0},
  {breed: 'Aegean', catName: 'Angel', id: 1},
  {breed: 'American Curl', catName: 'Annie', id: 2},
  {breed: 'American Bobtail', catName: 'Baby', id: 3},
  {breed: 'American Shorthair', catName: 'Bailey', id: 4},
  {breed: 'American Wirehair', catName: 'Bandit', id: 5},
  {breed: 'Arabian Mau', catName: 'Bear', id: 6},
  {breed: 'Australian Mist', catName: 'Bella', id: 7},
  {breed: 'Asian', catName: 'Bob', id: 8},
  {breed: 'Asian Semi-longhair', catName: 'Boo', id: 9},
  {breed: 'Balinese', catName: 'Boots', id: 10},
  {breed: 'Bambino', catName: 'Bubba', id: 11},
  {breed: 'Bengal', catName: 'Buddy', id: 12},
  {breed: 'Birman', catName: 'Buster', id: 13},
  {breed: 'Bombay', catName: 'Cali', id: 14},
  {breed: 'Brazilian Shorthair', catName: 'Callie', id: 15},
  {breed: 'British Semi-longhair', catName: 'Casper', id: 16},
  {breed: 'British Shorthair', catName: 'Charlie', id: 17},
  {breed: 'British Longhair', catName: 'Chester', id: 18},
  {breed: 'Burmese', catName: 'Chloe', id: 19},
  {breed: 'Burmilla', catName: 'Cleo', id: 20},
  {breed: 'California Spangled', catName: 'Coco', id: 21},
  {breed: 'Chantilly-Tiffany', catName: 'Cookie', id: 22},
  {breed: 'Chartreux', catName: 'Cuddles', id: 23},
  {breed: 'Chausie', catName: 'Daisy', id: 24},
  {breed: 'Cheetoh', catName: 'Dusty', id: 25},
  {breed: 'Colorpoint Shorthair', catName: 'Felix', id: 26},
  {breed: 'Cornish Rex', catName: 'Fluffy', id: 27},
  {breed: 'Cymric', catName: 'Garfield', id: 28},
  {breed: 'Cyprus', catName: 'George', id: 29},
  {breed: 'Devon Rex', catName: 'Ginger', id: 30},
  {breed: 'Donskoy', catName: 'Gizmo', id: 31},
  {breed: 'Dragon Li', catName: 'Gracie', id: 32},
  {breed: 'Dwarf cat', catName: 'Harley', id: 33},
  {breed: 'Egyptian Mau', catName: 'Jack', id: 34},
  {breed: 'European Shorthair', catName: 'Jasmine', id: 35},
  {breed: 'Exotic Shorthair', catName: 'Jasper', id: 36},
  {breed: 'Foldex', catName: 'Kiki', id: 37},
  {breed: 'German Rex', catName: 'Kitty', id: 38},
  {breed: 'Havana Brown', catName: 'Leo', id: 39},
  {breed: 'Highlander', catName: 'Lilly', id: 40},
  {breed: 'Himalayan', catName: 'Lily', id: 41},
  {breed: 'Japanese Bobtail', catName: 'Loki', id: 42},
  {breed: 'Javanese', catName: 'Lola', id: 43},
  {breed: 'Karelian Bobtail', catName: 'Lucky', id: 44},
  {breed: 'Khao Manee', catName: 'Lucy', id: 45},
  {breed: 'Korat', catName: 'Luna', id: 46},
  {breed: 'Korean Bobtail', catName: 'Maggie', id: 47},
  {breed: 'Korn Ja', catName: 'Max', id: 48},
  {breed: 'Kurilian Bobtail', catName: 'Mia', id: 49},
  {breed: 'LaPerm', catName: 'Midnight', id: 50},
  {breed: 'Lykoi', catName: 'Milo', id: 51},
  {breed: 'Maine Coon', catName: 'Mimi', id: 52},
  {breed: 'Manx', catName: 'Miss kitty', id: 53},
  {breed: 'Mekong Bobtail', catName: 'Missy', id: 54},
  {breed: 'Minskin', catName: 'Misty', id: 55},
  {breed: 'Munchkin', catName: 'Mittens', id: 56},
  {breed: 'Nebelung', catName: 'Molly', id: 57},
  {breed: 'Napoleon', catName: 'Muffin', id: 58},
  {breed: 'Norwegian Forest cat', catName: 'Nala', id: 59},
  {breed: 'Ocicat', catName: 'Oliver', id: 60},
  {breed: 'Ojos Azules', catName: 'Oreo', id: 61},
  {breed: 'Oregon Rex', catName: 'Oscar', id: 62},
  {breed: 'Oriental Bicolor', catName: 'Patches', id: 63},
  {breed: 'Oriental Shorthair', catName: 'Peanut', id: 64},
  {breed: 'Oriental Longhair', catName: 'Pepper', id: 65},
  {breed: 'PerFold', catName: 'Precious', id: 66},
  {breed: 'Persian (Modern Persian Cat)', catName: 'Princess', id: 67},
  {breed: 'Persian (Traditional Persian Cat)', catName: 'Pumpkin', id: 68},
  {breed: 'Peterbald', catName: 'Rascal', id: 69},
  {breed: 'Pixie-bob', catName: 'Rocky', id: 70},
  {breed: 'Raas', catName: 'Sadie', id: 71},
  {breed: 'Ragamuffin', catName: 'Salem', id: 72},
  {breed: 'Ragdoll', catName: 'Sam', id: 73},
  {breed: 'Russian Blue', catName: 'Samantha', id: 74},
  {breed: 'Russian White, Black and Tabby', catName: 'Sammy', id: 75},
  {breed: 'Sam Sawet', catName: 'Sasha', id: 76},
  {breed: 'Savannah', catName: 'Sassy', id: 77},
  {breed: 'Scottish Fold', catName: 'Scooter', id: 78},
  {breed: 'Selkirk Rex', catName: 'Shadow', id: 79},
  {breed: 'Serengeti', catName: 'Sheba', id: 80},
  {breed: 'Serrade petit', catName: 'Simba', id: 81},
  {breed: 'Siamese', catName: 'Simon', id: 82},
  {breed: 'Siberian', catName: 'Smokey', id: 83},
  {breed: 'Singapura', catName: 'Snickers', id: 84},
  {breed: 'Snowshoe', catName: 'Snowball', id: 85},
  {breed: 'Sokoke', catName: 'Snuggles', id: 86},
  {breed: 'Somali', catName: 'Socks', id: 87},
  {breed: 'Sphynx', catName: 'Sophie', id: 88},
  {breed: 'Suphalak', catName: 'Spooky', id: 89},
  {breed: 'Thai', catName: 'Sugar', id: 90},
  {breed: 'Thai Lilac', catName: 'Tiger', id: 91},
  {breed: 'Tonkinese', catName: 'Tigger', id: 92},
  {breed: 'Toyger', catName: 'Tinkerbell', id: 93},
  {breed: 'Turkish Angora', catName: 'Toby', id: 94},
  {breed: 'Turkish Van', catName: 'Trouble', id: 95},
  {breed: 'Ukrainian Levkoy', catName: 'Whiskers', id: 96},
];
