export const ADD_CAT_DETAILS = 'ADD_CAT_DETAILS';
export const EDIT_CAT_DETAILS = 'EDIT_CAT_DETAILS';
export const DELETE_CAT_DETAILS = 'DELETE_CAT_DETAILS';
export const SET_ALL_CAT_DATA = 'SET_ALL_CAT_DATA';
